#encoding: utf-8


__all__ = ['HTTP_HEADERS']


HTTP_HEADERS = (
      'accept',
      'accept-charset',
      'accept-encoding',
      'accept-language',
      'accept-ranges',
      'age',
      'allow',
      'authorization',
      'cache-control',
      'connection',
      'content-encoding',
      'content-language',
      'content-length',
      'content-location',
      'content-md5',
      'content-range',
      'content-type',
      'date',
      'etag',
      'expect',
      'expires',
      'from',
      'host',
      'if-match',
      'if-modified-since',
      'if-none-match',
      'if-range',
      'if-unmodified-since',
      'keep-alive',
      'last-modified',
      'location',
      'max-forwards',
      'pragma',
      'proxy-authenticate',
      'proxy-athorization',
      'range',
      'referer',
      'retry-after',
      'server',
      'te',
      'trailer',
      'transfer-encoding',
      'upgrade',
      'user-agent',
      'vary',
      'via',
      'warning',
      'www-authenticate',
      'cookie'
    )
